### ISSUE TITLE
Can not using compare with follow Readme.

### ISSUE THREAD

**Issue by XiaoqingNLP** [M4t1ss/SoftAlignments#33]
#### runing scripts

```
input=a.nematus 
input2=b.nematus
output_type=web


python process_alignments.py \
    -i $input \
    -o $output_type \
    -f Nematus \
    -v Nematus \
    -w $input2 \
```

#### error log 
process_alignments.py -i <input_file> [-o <output_type>] [-f <from_system>] [-s <source_sentence_file>] [-t <target_sentence_file>]
input_file is the file with alignment weights (required)
source_sentence_file and target_sentence_file are required only for NeuralMonkey
output_type can be web (default), block, block2 or color
from_system can be Nematus, Marian, Sockeye,  OpenNMT or NeuralMonkey (default)

**Comment by M4t1ss** [comment]
Hi!
Thanks!
Can you check if this works? https://github.com/M4t1ss/SoftAlignments/tree/bugfix

**Comment by XiaoqingNLP** [comment]
Thank you for your work, this version not given a error massage, but it does not work. It only display only one picture.

**Comment by M4t1ss** [comment]
Great, thanks! 
What do you mean by "one picture"? Is only one sentence being shown instead of two (looks like you wanted to compare 2)
In that case, you should use the "**compare**" output type instead of "**web**". It will still be the web version of the visualization - comparing only works in the web version.

**Comment by XiaoqingNLP** [comment]
Well Done,  yesterday I am too hurry to Too hasty to notice this detail. Thank your practical tools.
